
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import datetimechecker
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def testApp(day, month, year):
    window = Tk()
    result = False

    # window.geometry("862x519")
    window.configure(bg = "#3A7FF6")
    w = 862
    h = 519
    ws = window.winfo_screenwidth() # width of the screen
    hs = window.winfo_screenheight() # height of the screen

            # calculate x and y coordinates for the Tk root window
    x = (ws/2) - (w/2)
    y = (hs/2) - (h/2)

            # set the dimensions of the screen 
            # and where it is placed
    window.geometry('%dx%d+%d+%d' % (w, h, x, y))


    canvas = Canvas(
        window,
        bg = "#3A7FF6",
        height = 519,
        width = 862,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        431.0,
        0.0,
        862.0,
        519.0,
        fill="#FFFFFF",
        outline="")

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        653.0,
        272.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#F1F1F1",
        highlightthickness=0
    )
    entry_1.place(
        x=503.0,
        y=249.0,
        width=300.0,
        height=44.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        653.0,
        353.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#F1F1F1",
        highlightthickness=0
    )
    entry_2.place(
        x=503.0,
        y=330.0,
        width=300.0,
        height=44.0
    )

    canvas.create_text(
        498.0,
        219.0,
        anchor="nw",
        text="Month",
        fill="#000000",
        font=("Laila Regular", 16 * -1)
    )

    canvas.create_text(
        498.0,
        300.0,
        anchor="nw",
        text="Year",
        fill="#000000",
        font=("Laila Regular", 16 * -1)
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        653.0,
        184.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#F1F1F1",
        highlightthickness=0
    )
    entry_3.place(
        x=503.0,
        y=161.0,
        width=300.0,
        height=44.0
    )

    canvas.create_text(
        498.0,
        132.0,
        anchor="nw",
        text="Day",
        fill="#000000",
        font=("Laila Regular", 16 * -1)
    )

    canvas.create_text(
        552.0,
        53.0,
        anchor="nw",
        text="Date Time Checker",
        fill="#000000",
        font=("Laila Bold", 20 * -1)
    )

    canvas.create_text(
        29.0,
        168.0,
        anchor="nw",
        text="Welcome to Date Time Checker App",
        fill="#FFFFFF",
        font=("Laila Bold", 20 * -1)
    )

    canvas.create_rectangle(
        29.0,
        202.0,
        89.0,
        207.0,
        fill="#FFFFFF",
        outline="")

    entry_1.insert(0, str(month))
    entry_3.insert(0, str(day))
    entry_2.insert(0, str(year))
    btnCheckCicked = True

    if btnCheckCicked == True:
        intMonth = int(entry_1.get())
        intDay = int(entry_3.get())
        intYear = int(entry_2.get())
        if datetimechecker.isValidDate(intYear, intMonth, intDay):
            canvas.create_text(
                625.0,
                100.0,
                anchor="nw",
                text="Valid!",
                fill="#17c39b",
                font=("Laila Bold", 20 * -1)
            )
            result = True

        else:
            canvas.create_text(
                625.0,
                100.0,
                anchor="nw",
                text="Invalid!",
                fill="#ff0000",
                font=("Laila Bold", 20 * -1)
            )
            result = False

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        relief="flat"
    )
    button_1.place(
        x=587.0,
        y=424.0,
        width=146.0,
        height=36.0
    )

    canvas.create_text(
        29.0,
        237.0,
        anchor="nw",
        text="Date Time Checker is the app that created to check ",
        fill="#FFFFFF",
        font=("Laila", 16 * -1)
    )

    canvas.create_text(
        29.0,
        265.0,
        anchor="nw",
        text="3 input data such as day, month, year that is",
        fill="#FFFFFF",
        font=("Laila", 16 * -1)
    )

    canvas.create_text(
        29.0,
        293.0,
        anchor="nw",
        text="suitable or not.",
        fill="#FFFFFF",
        font=("Laila", 16 * -1)
    )

    canvas.create_text(
        29.0,
        351.0,
        anchor="nw",
        text="Date Time Checker is created using Python.",
        fill="#FFFFFF",
        font=("Laila", 16 * -1)
    )
    window.after(2000,lambda:window.destroy())
    window.resizable(False, False)
    window.mainloop()
    return result
